### ISSUE TITLE
No audio output for plugins under Linux

### ISSUE THREAD

**Issue by gjones007** [FigBug/Wavetable#19]
The LV2 and VST3 plugins (1.02) on Linux (Fedora 38 using Reaper 6.82) the plugin shows 2 input channels, no audio output channels.  Everything appears to be running, but no audio output is generated.  The standalone binary works.

Same version of the VST3 plugin on Windows using  Reaper 6.82 shows 2 channels of output, and works.

**Comment by FigBug** [comment]
Did you build yourself or use binaries I built?

**Comment by FigBug** [comment]
Can you try https://github.com/FigBug/Wavetable/releases and let me know if it fixes it?

**Comment by FigBug** [comment]
Maybe fixed in 681be5731b4e50b9ecd9754f08406d5c60de0400

**Comment by gjones007** [comment]
Sorry for the delay, yes that did fix the issue!  Thank you!
