### ISSUE TITLE
Libc issue on Debian Bullseye

### ISSUE THREAD

**Issue by erwan35** [FigBug/Wavetable#33]
Hello,

Thanks for this cool plugin !

I'm trying to use the lv2 version on Debian Bullseye (inside Carla) but there's a libc mismatch (2.31-13+deb11u6)

![glibc](https://github.com/FigBug/Wavetable/assets/4410119/88d42188-d9aa-44d2-ad3d-6dca00a0a297)

Do you think of anything that could avoid this ?

Cheers
Erwan

**Comment by FigBug** [comment]
Did you build yourself or use my binaries?

**Comment by erwan35** [comment]
I used the binary (my cmake version is too old)
 
`CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.24.0 or higher is required.  You are running version 3.18.4`

**Comment by FigBug** [comment]
I've tried statically linking c++ standard library
I've also rolled back cmake requirement to 3.16
do either of those solve it for you?

**Comment by erwan35** [comment]
Hello,

1.0.10 binary (lv2) is loading now !

I have try to compile it but i'm getting this : 
`  CMake 3.22 or higher is required.  You are running version 3.18.4`

Let's have fun now :)

Thanks
