### ISSUE TITLE
VST2-Version 1.0.9: Pitchbend doesn't seem to work at all (VST3 is ok)

### ISSUE THREAD

**Issue by pohlw** [FigBug/Wavetable#41]
DAW: Ableton 11

**Comment by FigBug** [comment]
MPE on or off?

**Comment by pohlw** [comment]
Not sure where to check. Using Non-MPE MIDI-Controller. To reproduce: 1. use Patch "NylonSteel" in both cases; 2. Load VST2 into DAW - no Pitchbend Response; 3. Load VST3 into DAW: Ptchbend works.
