### ISSUE TITLE
[Feature request] Microtonal support

### ISSUE THREAD

**Issue by tank-trax** [FigBug/Wavetable#48]
Either or both would be great.

SCL/KBM support

https://github.com/surge-synthesizer/tuning-library

MTS-ESP

https://github.com/ODDSound/MTS-ESP

Thanks

**Comment by eventual-recluse** [comment]
I had a go at adding MTS-ESP to Wavetable. I've put a guide with instructions and edited source here: https://github.com/eventual-recluse/MTS-ESP-Guides

Tuning is continuous, so currently playing notes will change when the MTS-ESP scale changes.

The changes are fairly straightforward. MTS-ESP needs to be added as another module with its own CMakeLists.txt. There are also some changes to the main CMakeLists.txt. Apart from that there's just a few changes to plugin/Source/WavetableVoice.h and WavetableVoice.cpp.

I'm not so familiar with JUCE, so haven't made any other changes to the .jucer project or anything like that...

**Comment by FigBug** [comment]
Added MTS-ESP

@eventual-recluse I made a few changes to how you implemented it

**Comment by eventual-recluse** [comment]
Excellent! Wavetable is a fantastic synth & great to have MTS-ESP support. Thank you!

**Comment by FigBug** [comment]
Not sure why VST3 would be any different that VST or LV2

**Comment by eventual-recluse** [comment]
I tried the VST3 (built from source) and there's no issue on my system (Fedora Linux). MTS-ESP is working fine.

**Comment by tank-trax** [comment]
Thanks for checking. I will test it again in Bitiwg this time. I was trying it in Reaper and there's a setting I may need to enable for the IPC to work.

**Comment by tank-trax** [comment]
My bad. Had two Wavetable VST3's in the ~/.vst3 folder

It's working. Will close this. Thanks!!!
